version: '3'
services:
  web:
    build: .
    ports:
      - "8008:8008"
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: postgres
      POSTGRES_DB: Grosery-Booking